# -*- coding: utf-8 -*-
"""Desafio-Aula-Inaugural.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x3mXdzUnPH3YCVp8WPkOioyh-Zz9rZ9_
"""

# prompt: importar bibliotecas de panda

import pandas as pd
import sklearn as sk
import matplotlib as plot
import seaborn as sns
import numpy as np
from sklearn.metrics import accuracy_score, classification_report
from sklearn.ensemble import RandomForestClassifier

df = pd.read_csv('dropout-inaugural.csv')

df.head(2)

print(df.info())

df.Target.value_counts()

df = df.drop_duplicates()
df = df.fillna(0)

sns.barplot(df.Gender.value_counts())

X = df.drop('Target', axis=1)
y = df['Target']
X_train, X_test, y_train, y_test = sk.model_selection.train_test_split(X, y, test_size=0.3, random_state=42)


# Criar o modelo
rf_model = RandomForestClassifier(random_state=42)

# Treinar
rf_model.fit(X_train, y_train)

# Prever
y_pred_rf = rf_model.predict(X_test)

# Avaliar
print("Acurácia:", accuracy_score(y_test, y_pred_rf))
print("Relatório:\n", classification_report(y_test, y_pred_rf))